server.port=8081
spring.application.name=api-gateway

spring.cloud.gateway.mvc.routes[0].id=ms-usuarios-auth
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8083
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth,/api/auth/**

spring.cloud.gateway.mvc.routes[1].id=ms-usuarios-identidad
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8083
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/usuarios,/api/usuarios/**

spring.cloud.gateway.mvc.routes[2].id=ms-catalogo-productos
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8084
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/productos,/api/productos/**

spring.cloud.gateway.mvc.routes[3].id=ms-catalogo-categorias
spring.cloud.gateway.mvc.routes[3].uri=http://localhost:8084
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/categorias,/api/categorias/**

spring.cloud.gateway.mvc.routes[4].id=ms-inventario
spring.cloud.gateway.mvc.routes[4].uri=http://localhost:8085
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/inventario,/api/inventario/**

spring.cloud.gateway.mvc.routes[5].id=ms-stock
spring.cloud.gateway.mvc.routes[5].uri=http://localhost:8085
spring.cloud.gateway.mvc.routes[5].predicates[0]=Path=/api/stock,/api/stock/**

spring.cloud.gateway.mvc.routes[6].id=ms-pedidos
spring.cloud.gateway.mvc.routes[6].uri=http://localhost:8086
spring.cloud.gateway.mvc.routes[6].predicates[0]=Path=/api/pedidos,/api/pedidos/**

spring.cloud.gateway.mvc.routes[7].id=ms-ventas
spring.cloud.gateway.mvc.routes[7].uri=http://localhost:8086
spring.cloud.gateway.mvc.routes[7].predicates[0]=Path=/api/ventas,/api/ventas/**

spring.cloud.gateway.mvc.routes[8].id=ms-envios
spring.cloud.gateway.mvc.routes[8].uri=http://localhost:8087
spring.cloud.gateway.mvc.routes[8].predicates[0]=Path=/api/envios,/api/envios/**

spring.cloud.gateway.mvc.routes[9].id=ms-rutas
spring.cloud.gateway.mvc.routes[9].uri=http://localhost:8087
spring.cloud.gateway.mvc.routes[9].predicates[0]=Path=/api/rutas,/api/rutas/**

spring.cloud.gateway.mvc.routes[10].id=ms-admin
spring.cloud.gateway.mvc.routes[10].uri=http://localhost:8088
spring.cloud.gateway.mvc.routes[10].predicates[0]=Path=/api/admin,/api/admin/**

spring.cloud.gateway.mvc.routes[11].id=ms-soporte
spring.cloud.gateway.mvc.routes[11].uri=http://localhost:8088
spring.cloud.gateway.mvc.routes[11].predicates[0]=Path=/api/soporte,/api/soporte/**

spring.cloud.gateway.mvc.routes[12].id=ms-reportes
spring.cloud.gateway.mvc.routes[12].uri=http://localhost:8089
spring.cloud.gateway.mvc.routes[12].predicates[0]=Path=/api/v1/reportes,/api/v1/reportes/**

spring.cloud.gateway.mvc.routes[13].id=ms-kpis
spring.cloud.gateway.mvc.routes[13].uri=http://localhost:8089
spring.cloud.gateway.mvc.routes[13].predicates[0]=Path=/api/v1/kpis,/api/v1/kpis/**

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.web=INFO
