server.port=8081
spring.application.name=api-gateway

spring.cloud.gateway.server.webmvc.routes[0].id=ms-usuarios-auth
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth,/api/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=ms-usuarios-identidad
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/usuarios,/api/usuarios/**

spring.cloud.gateway.server.webmvc.routes[2].id=ms-catalogo-productos
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/productos,/api/productos/**

spring.cloud.gateway.server.webmvc.routes[3].id=ms-catalogo-categorias
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/categorias,/api/categorias/**

spring.cloud.gateway.server.webmvc.routes[4].id=ms-inventario
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/inventario,/api/inventario/**

spring.cloud.gateway.server.webmvc.routes[5].id=ms-stock
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/stock,/api/stock/**

spring.cloud.gateway.server.webmvc.routes[6].id=ms-pedidos
spring.cloud.gateway.server.webmvc.routes[6].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/pedidos,/api/pedidos/**

spring.cloud.gateway.server.webmvc.routes[7].id=ms-ventas
spring.cloud.gateway.server.webmvc.routes[7].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/ventas,/api/ventas/**

spring.cloud.gateway.server.webmvc.routes[8].id=ms-envios
spring.cloud.gateway.server.webmvc.routes[8].uri=http://localhost:8087
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/api/envios,/api/envios/**

spring.cloud.gateway.server.webmvc.routes[9].id=ms-rutas
spring.cloud.gateway.server.webmvc.routes[9].uri=http://localhost:8087
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/api/rutas,/api/rutas/**

spring.cloud.gateway.server.webmvc.routes[10].id=ms-admin
spring.cloud.gateway.server.webmvc.routes[10].uri=http://localhost:8088
spring.cloud.gateway.server.webmvc.routes[10].predicates[0]=Path=/api/admin,/api/admin/**

spring.cloud.gateway.server.webmvc.routes[11].id=ms-soporte
spring.cloud.gateway.server.webmvc.routes[11].uri=http://localhost:8088
spring.cloud.gateway.server.webmvc.routes[11].predicates[0]=Path=/api/soporte,/api/soporte/**

spring.cloud.gateway.server.webmvc.routes[12].id=ms-reportes
spring.cloud.gateway.server.webmvc.routes[12].uri=http://localhost:8090
spring.cloud.gateway.server.webmvc.routes[12].predicates[0]=Path=/api/v1/reportes,/api/v1/reportes/**

spring.cloud.gateway.server.webmvc.routes[13].id=ms-kpis
spring.cloud.gateway.server.webmvc.routes[13].uri=http://localhost:8090
spring.cloud.gateway.server.webmvc.routes[13].predicates[0]=Path=/api/v1/kpis,/api/v1/kpis/**
spring.cloud.gateway.server.webmvc.routes[14].id=ms-catalogo-resenas
spring.cloud.gateway.server.webmvc.routes[14].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[14].predicates[0]=Path=/api/resenas,/api/resenas/**

spring.cloud.gateway.server.webmvc.routes[15].id=ms-pedidos-devoluciones
spring.cloud.gateway.server.webmvc.routes[15].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[15].predicates[0]=Path=/api/devoluciones,/api/devoluciones/**

spring.cloud.gateway.server.webmvc.routes[16].id=ms-pedidos-reclamaciones
spring.cloud.gateway.server.webmvc.routes[16].uri=http://localhost:8086
spring.cloud.gateway.server.webmvc.routes[16].predicates[0]=Path=/api/reclamaciones,/api/reclamaciones/**

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.org.springframework.cloud.gateway=INFO
logging.level.org.springframework.web=INFO
