spring.application.name=ms-reportes
server.port=8087

spring.datasource.url=${REPORTES_DB_URL:jdbc:postgresql://localhost:5432/bd_reportes}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
