spring.application.name=ms-administracion-soporte
server.port=8086

spring.datasource.url=${ADMIN_DB_URL:jdbc:postgresql://localhost:5432/bd_admin}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
